language: haxe

haxe:
  - stable

install:
  - yes | haxelib install test.hxml
  - yes | haxelib install example-readme.hxml

script:
  - haxe hxml/test.neko.hxml
  - neko out/neko/test.n
  - haxe example-readme.hxml
